### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by alirasoli** [twitter/vireo#28]
Hello,
I was looking for a tool to cut video without re-encoding in none key-frames and found vireo.

I used this command to trim a video:
`trim "23000" "14000" "1.mp4" "3.mp4"`
but it gives me this output:
`Segmentation fault (core dumped)`
What is the problem?

**Comment by canbal** [comment]
Can you share the inputs you used? If you're seeing a segfault we should fix it.

**Comment by alirasoli** [comment]
While compiling vireo I got a linker error so I used this to change makefile:
`sed -i 's+-llsmash+/usr/lib/liblsmash.a+g' Makefile`

Then used trim like this:
`trim "23000" "14000" "1.mp4" "3.mp4"`
and got Segmentation fault (core dumped)

This is gdb backtrace for my input:
`#0  0x0000555555572c41 in nalu_import_rbsp_from_ebsp ()
#1  0x000055555556dd5f in ?? ()
#2  0x000055555556e923 in h264_parse_sps ()
#3  0x00007ffff7b8fbb0 in vireo::internal::demux::_MP4::parse_pixel_aspect_ratio (
    par=<synthetic pointer>..., sps=..., this=0x555555808d20)
    at internal/demux/mp4.cpp:215
#4  vireo::internal::demux::_MP4::parse_video_resolution (track_param=..., 
    this=0x555555808d20) at internal/demux/mp4.cpp:195
#5  vireo::internal::demux::_MP4::finish_initialization (this=0x555555808d20)
    at internal/demux/mp4.cpp:600
#6  0x00007ffff7b85655 in vireo::internal::demux::MP4::MP4 (this=0x555555808c20, 
    reader=...) at internal/demux/mp4.cpp:687
#7  0x00007ffff7b65a38 in vireo::demux::_Movie::parse<(vireo::FileType)1, (void*)0> (
    this=0x5555558086d0, reader=...) at demux/movie.cpp:95
#8  0x00007ffff7b5dbbd in vireo::demux::Movie::Movie (this=0x7fffffffd5f0, reader=...)
    at demux/movie.cpp:171
#9  0x0000555555567367 in main (argc=<optimized out>, argv=<optimized out>)
    at tools/trim/main.cpp:56`

I tested this on two devices with ubuntu 18.04 64bit and got same error.
